# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

runs:
  using: 'docker'
  image: 'Dockerfile'
  ports:
  # Opens tcp port 6379 on the host and service container
  - 9090:9090